djangoblog/blogapp/urls.py
from django.urls import path
from . import views
app_name="blogapp"

urlpatterns = [
    path('', views.index.as_view(), name="index"),
    path('author/<name>', views.getauthor.as_view(), name="author"),
    path('article/<int:id>', views.getsingle.as_view(), name="single_post"),
    path('topic/<name>', views.getTopic, name="topic"),
    path('login', views.getLogin.as_view(), name="login"),
    path('logout', views.getlogout, name="logout"),
    path('create', views.getcreate, name="create"),
    path('profile', views.getProfile, name="profile"),
    path('update/<int:pid>', views.getUpdate, name="update"),
    path('delete/<int:pid>', views.getDelete, name="delete"),
    path('register', views.getRegister, name="register"),
    path('topics', views.getCategory, name="category"),
    path('create/topic', views.createTopic, name="createTopic"),



    #account confirmations
    path('activate/<uid>/<token>', views.activate, name="activate")
]

djangoblog/djangoblog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("blogapp.urls", namespace="blog")),
    path('ckeditor/',include("ckeditor_uploader.urls"))
]

if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

djangoblog/templates/base.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
	<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>{% block title %}{% endblock %}</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="Free HTML5 Template by FREEHTML5.CO" />
	<meta name="keywords" content="free html5, free template, free bootstrap, html5, css3, mobile first, responsive" />
	<meta name="author" content="FREEHTML5.CO" />

  <!--
	//////////////////////////////////////////////////////

	FREE HTML5 TEMPLATE
	DESIGNED & DEVELOPED by FREEHTML5.CO

	Website: 		http://freehtml5.co/
	Email: 			info@freehtml5.co
	Twitter: 		http://twitter.com/fh5co
	Facebook: 		https://www.facebook.com/fh5co

	//////////////////////////////////////////////////////
	 -->

  	<!-- Facebook and Twitter integration -->
	<meta property="og:title" content=""/>
	<meta property="og:image" content=""/>
	<meta property="og:url" content=""/>
	<meta property="og:site_name" content=""/>
	<meta property="og:description" content=""/>
	<meta name="twitter:title" content="" />
	<meta name="twitter:image" content="" />
	<meta name="twitter:url" content="" />
	<meta name="twitter:card" content="" />

	<!-- Place favicon.ico and apple-touch-icon.png in the root directory -->
	<link rel="shortcut icon" href="favicon.ico">
	<!-- Google Fonts -->
	<link href='http://fonts.googleapis.com/css?family=Playfair+Display:400,700,400italic|Roboto:400,300,700' rel='stylesheet' type='text/css'>
	<!-- Animate -->
        {% load static %}
	<link rel="stylesheet" href="{% static 'css/animate.css' %}">
	<!-- Icomoon -->
	<link rel="stylesheet" href="{% static 'css/icomoon.css' %}">
	<!-- Bootstrap  -->
	<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">

	<link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% block stylesheet %}

    {% endblock %}


	<!-- Modernizr JS -->
	<script src="{% static 'js/modernizr-2.6.2.min.js' %}"></script>
	<!-- FOR IE9 below -->
	<!--[if lt IE 9]>
	<script src="{% static 'js/respond.min.js' %}"></script>
	<![endif]-->

	</head>
	<body>
	<div id="fh5co-offcanvas">
		<a href="#" class="fh5co-close-offcanvas js-fh5co-close-offcanvas"><span><i class="icon-cross3"></i> <span>Close</span></span></a>
        {% block profile %}

        {% endblock %}
		<div class="fh5co-menu">
			<div class="fh5co-box">
				<h3 class="heading">Menu</h3>
				<ul>
					<li><a href="#">Blog</a></li>
                    <li><a href="{% url 'blog:category' %}">Category</a></li>
					{% if request.user.is_authenticated %}
                        <li><a href="{% url 'blog:profile' %}">Profile</a></li>
                        <li><a href="{% url 'blog:logout' %}">Logout</a></li>
                        {% else %}
                        <li><a href="{% url 'blog:login' %}">Login</a></li>
                    {% endif %}
				</ul>
			</div>
			<div class="fh5co-box">
				<h3 class="heading">Search</h3>
				<form action="" method="GET">
					<div class="form-group">
						<input type="text" name="q" class="form-control" placeholder="Type a keyword" value="{{ request.GET.q }}">
					</div>
				</form>
			</div>
		</div>
	</div>
	<!-- END #fh5co-offcanvas -->
	<header id="fh5co-header">

		<div class="container-fluid">

			<div class="row">
				<a href="#" class="js-fh5co-nav-toggle fh5co-nav-toggle"><i></i></a>
				<ul class="fh5co-social">
					<li><a href="#"><i class="icon-twitter"></i></a></li>
					<li><a href="#"><i class="icon-facebook"></i></a></li>
					<li><a href="#"><i class="icon-instagram"></i></a></li>
				</ul>
				<div class="col-lg-12 col-md-12 text-center">
					<h1 id="fh5co-logo"><a href="{% url 'blog:index' %}">Blog</a></h1>
				</div>

			</div>

		</div>

	</header>
    <div class="container-fluid">
		<div class="row fh5co-post-entry">
    {% block content %}

    {% endblock %}
        </div>
    </div>


	<footer id="fh5co-footer">
		<p><small>&copy; 2016. Magazine Free HTML5. All Rights Reserverd. <br> Designed by <a href="http://freehtml5.co" target="_blank">FREEHTML5.co</a>  Demo Images: <a href="http://unsplash.com/" target="_blank">Unsplash</a></small></p>
	</footer>



	<!-- jQuery -->
	<script src="{% static 'js/jquery.min.js' %}"></script>
	<!-- jQuery Easing -->
	<script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
	<!-- Bootstrap -->
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
	<!-- Waypoints -->
	<script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
	<!-- Main JS -->
	<script src="{% static 'js/main.js' %}"></script>
    {% block script %}{% endblock %}
	</body>
</html>

djangoblog/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Welcome to our django blog{% endblock %}
{% block stylesheet %}{% endblock %}
{% block content %}
    <h4 class="container">Category: {{ cat.name }}</h4>
    {% for p in post %}
        <article class="col-lg-3 col-md-3 col-sm-3 col-xs-6 col-xxs-12 animate-box">
            <figure>
                <a href="{% url 'blog:single_post' id=p.id %}"><img src="{{ p.image.url }}" alt="Image" class="img-responsive"></a>
            </figure>
            <span class="fh5co-meta"><a href="{% url 'blog:topic' name=p.category.name %}">{{ p.category.name }}</a></span>
            <h2 class="fh5co-article-title"><a href="{% url 'blog:single_post' id=p.id %}">{{ p.title }}</a></h2>
            <span class="fh5co-meta fh5co-date">{{ p.posted_on }}</span>
        </article>
    {% endfor %}

<div class="container-fluid">
    <div class="pagination">
    <span class="step-links">
        {% if post.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ post.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ post.number }} of {{ post.paginator.num_pages }}.
        </span>

        {% if post.has_next %}
            <a href="?page={{ post.next_page_number }}">next</a>
            <a href="?page={{ post.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>
    </div>
{% endblock %}
{% block script %}

{% endblock %}

djangoblog/templates/confirm_email.html
{% autoescape off %}
Hi {{ user.username }},
Thanks for your registration in blog
Please click on the link below to confirm your registration,
http://{{ domain }}{% url 'blog:activate' uid=uid token=token %}
{% endautoescape %}

djangoblog/templates/create_topics.html
{% extends 'base.html' %}
{% block title %}

{% endblock %}
{% block stylesheet %}

{% endblock %}
{% block profile %}
{% endblock %}
{% block content %}
<div class="container">
    <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-primary">Create category</button>
    </form>
</div>
{% endblock %}
{% block script %}

{% endblock %}

djangoblog/templates/createauthor.html
{% extends 'base.html' %}
{% block title %}
Create author profile
{% endblock %}
{% block stylesheet %}

{% endblock %}
{% block profile %}
{% endblock %}
{% block content %}
<div class="container">
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-primary">Create author</button>
    </form>
</div>
{% endblock %}
{% block script %}

{% endblock %}

djangoblog/templates/getAuthorInfo.html
{% extends 'base.html' %}
{% block title %}
Create author profile
{% endblock %}
{% block stylesheet %}

{% endblock %}
{% block profile %}
{% endblock %}
{% block content %}
<div class="container">
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-primary">Create author</button>
    </form>
</div>
{% endblock %}
{% block script %}

{% endblock %}

djangoblog/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Welcome to our django blog{% endblock %}
{% block stylesheet %}{% endblock %}
{% block content %}
	<!-- END #fh5co-header -->
    <div class="allpost">
    {% for p in post %}
        <article class="col-lg-3 col-md-3 col-sm-3 col-xs-6 col-xxs-12 animate-box">
            <figure>
                <a href="{{ p.get_single_url }}"><img src="{{ p.image.url }}" alt="Image" class="img-responsive"></a>
            </figure>
            <span class="fh5co-meta"><a href="{% url 'blog:topic' name=p.category.name %}">{{ p.category.name }}</a></span>
            <h2 class="fh5co-article-title"><a href="{{ p.get_single_url }}">{{ p.title }}</a></h2>
            <h4><a href="{{ p.get_author_url }}">{{ p.article_author.name.get_full_name }}</a></h4>
            <span class="fh5co-meta fh5co-date">{{ p.posted_on }}</span>
        </article>
    {% endfor %}
    <div class="clear-fix"></div>
    </div>
    <div class="pagination">
    <span class="step-links">
        {% if post.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ post.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ post.number }} of {{ post.paginator.num_pages }}.
        </span>

        {% if post.has_next %}
            <a href="?page={{ post.next_page_number }}">next</a>
            <a href="?page={{ post.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>
{% endblock %}
{% block script %}

{% endblock %}

djangoblog/templates/logged_in_profile.html
{% extends 'base.html' %}
{% block title %}
{{ user.name.get_full_name }}
{% endblock %}
{% block stylesheet %}
    <style>
    .alert {
    height: 50px;
    margin-top: 200px;
}
    </style>
{% endblock %}
{% block profile %}
    <div class="fh5co-bio">
			<figure>
				<img src="{{ user.profile_picture.url }}" alt="Free HTML5 Bootstrap Template" class="img-responsive">
			</figure>
			<h3 class="heading">About Me</h3>
			<h2>{{ user.name.get_full_name }}</h2>
            <h4>{{ user.name.email }}</h4>
			<p>{{ user.details }}</p>
			<ul class="fh5co-social">
				<li><a href="#"><i class="icon-twitter"></i></a></li>
				<li><a href="#"><i class="icon-facebook"></i></a></li>
				<li><a href="#"><i class="icon-instagram"></i></a></li>
			</ul>
		</div>
{% endblock %}
{% block content %}
    {% if messages %}
    <div class="messages">
        {% for message in messages %}
        <div {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</div>
        {% endfor %}
    </div>
    {% endif %}
    <div class="container">
        <a href="{% url 'blog:create' %}" class="btn btn-primary pull pull-right">Add new article</a>
    <table class="table table-striped">
        <thead>
        <tr>
            <td>Title</td>
            <td>Posted On</td>
            <td>Action</td>
        </tr>
        </thead>
        <tbody>
        {% for p in post %}
            <tr>
                <td>{{ p.title }}</td>
                <td>{{ p.posted_on }}</td>
                <td><a href="{% url 'blog:delete' pid=p.id %}">Delete</a>||<a href="{% url 'blog:update' pid=p.id %}">Edit</a></td>
            </tr>
        {% endfor %}

        </tbody>
</table>
    </div>
{% endblock %}
{% block script %}

{% endblock %}

djangoblog/templates/login.html
{% extends 'base.html' %}
{% block title %}Please login{% endblock %}
{% block stylesheet %}
{% endblock %}
{% block profile %}
{% endblock %}
{% block content %}
<div class="container-fluid">
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">Please login to your account</h3>
          </div>
          <div class="panel-body">
              {% if messages %}
                <div class="messages">
                    {% for message in messages %}
                    <div {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</div>
                    {% endfor %}
                </div>
                {% endif %}
            <form action="" method="POST">
                {% csrf_token %}
              <div class="form-group">
                <label for="exampleInputEmail1">Username</label>
                <input type="text" name="user" class="form-control" id="exampleInputEmail1" placeholder="Email">
              </div>
              <div class="form-group">
                <label for="exampleInputPassword1">Password</label>
                <input type="password" name="pass" class="form-control" id="exampleInputPassword1" placeholder="Password">
              </div>

              <button type="submit" class="btn btn-default">Login</button>
              <p>Are you new here? <a href="{% url 'blog:register' %}">Register now</a></p>
            </form>
          </div>
        </div>
    </div>
</div>
</div>
{% endblock %}
{% block script %}

{% endblock %}

djangoblog/templates/profile.html
{% extends 'base.html' %}
{% block title %}
    Author || {{ auth.name.get_full_name }}
{% endblock %}
{% block stylesheet %}
<style type="text/css">
		#fh5co-offcanvas {
    width: auto;
}
#fh5co-offcanvas .fh5co-menu, #fh5co-offcanvas .fh5co-bio {
    width: auto;
    padding: 50px;
}
    </style>
{% endblock %}
{% block profile %}
    <div class="fh5co-bio">
			<figure>
				<img src="{{ auth.profile_picture.url }}" alt="Free HTML5 Bootstrap Template" class="img-responsive">
			</figure>
			<h3 class="heading">About Me</h3>
			<h2>{{ auth.name.get_full_name }}</h2>
			<p>{{ auth.details }}</p>
			<ul class="fh5co-social">
				<li><a href="#"><i class="icon-twitter"></i></a></li>
				<li><a href="#"><i class="icon-facebook"></i></a></li>
				<li><a href="#"><i class="icon-instagram"></i></a></li>
			</ul>
		</div>
{% endblock %}
{% block content %}
    <h1>Author: {{ auth.name.get_full_name }}</h1>
    {% for p in post %}
        <article class="col-lg-3 col-md-3 col-sm-3 col-xs-6 col-xxs-12 animate-box">
            <figure>
                <a href="{% url 'blog:single_post' id=p.id %}"><img src="{{ p.image.url }}" alt="Image" class="img-responsive"></a>
            </figure>
            <span class="fh5co-meta"><a href="{% url 'blog:topic' name=p.category.name %}">{{ p.category }}</a></span>
            <h2 class="fh5co-article-title"><a href="{% url 'blog:single_post' id=p.id %}">{{ p.title }}</a></h2>
            <span class="fh5co-meta fh5co-date">{{ p.posted_on }}</span>
        </article>
    {% endfor %}

{% endblock %}
{% block script %}

{% endblock %}

djangoblog/templates/register.html
{% extends 'base.html' %}
{% block title %}
Please register for new account
{% endblock %}
{% block stylesheet %}

{% endblock %}
{% block profile %}
{% endblock %}
{% block content %}
    <div class="container">
        <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
            <button class="btn btn-primary">Register</button>
        </form>
    </div>
{% endblock %}
{% block script %}

{% endblock %}

djangoblog/templates/sample.html
{% extends 'base.html' %}
{% block title %}

{% endblock %}
{% block stylesheet %}

{% endblock %}
{% block profile %}
{% endblock %}
{% block content %}

{% endblock %}
{% block script %}

{% endblock %}

djangoblog/templates/single.html
{% extends 'base.html' %}
{% block title %}
{{ post.title }}
{% endblock %}
{% block stylesheet %}
    <style>
    div.single_comment p {
    background: #eaeaea;
    padding: 20px;
}
    </style>
{% endblock %}
{% block profile %}
    <div class="fh5co-bio">
			<figure>
				<img src="{{ post.article_author.profile_picture.url }}" alt="Free HTML5 Bootstrap Template" class="img-responsive">
			</figure>
			<h3 class="heading">About Me</h3>
			<h2>{{ post.article_author.name.get_full_name }}</h2>
            <h4>{{ post.article_author.name.email }}</h4>
			<p>{{ post.article_author.details }}</p>
			<ul class="fh5co-social">
				<li><a href="#"><i class="icon-twitter"></i></a></li>
				<li><a href="#"><i class="icon-facebook"></i></a></li>
				<li><a href="#"><i class="icon-instagram"></i></a></li>
			</ul>
		</div>
{% endblock %}
{% block content %}
	{% if post.id > first.id %}
	<a href="{% url 'blog:single_post' id=post.id|add:'-1' %}" class="fh5co-post-prev"><span><i class="icon-chevron-left"></i> Prev</span></a>
	{% endif %}
	{% if post.id < last.id %}
        <a href="{% url 'blog:single_post' id=post.id|add:'1' %}" class="fh5co-post-next"><span>Next <i class="icon-chevron-right"></i></span></a>

	{% endif %}
	<!-- END #fh5co-header -->
	<div class="container-fluid">
		<div class="row fh5co-post-entry single-entry">
			<article class="col-lg-8 col-lg-offset-2 col-md-8 col-md-offset-2 col-sm-8 col-sm-offset-2 col-xs-12 col-xs-offset-0">
				<figure class="animate-box">
					<img src="{{ post.image.url }}" alt="Image" class="img-responsive">
				</figure>
				<span class="fh5co-meta animate-box"><a href="{% url 'blog:topic' name=post.category.name %}">{{ post.category.name }}</a></span>
				<h2 class="fh5co-article-title animate-box">{{ post.title }}</h2>
				<span class="fh5co-meta fh5co-date animate-box">{{ post.posted_on }}</span>
				
				<div class="col-lg-12 col-lg-offset-0 col-md-12 col-md-offset-0 col-sm-12 col-sm-offset-0 col-xs-12 col-xs-offset-0 text-left content-article">
					<div class="row">
						<div class="col-lg-12 cp-r animate-box">
                            <p>{{ post.body|safe }}</p>
						</div>

					</div>

				</div>
			</article>
		</div>
        <div class="container">
            <h3 class="well">Related article</h3>
            <div class="row">
                {% for r in related %}
                    <div class="col-md-3">
                        <figure class="animate-box">
                            <a href="{% url 'blog:single_post' id=r.id %}"><img src="{{ r.image.url }}" alt="Image" class="img-responsive"></a>
                            <a href="{% url 'blog:single_post' id=r.id %}"><h2 class="fh5co-article-title animate-box">{{ r.title }}</h2></a>
                            <p>{{ r.body|truncatewords:15 }}</p>
                        </figure>
                    </div>
                {% endfor %}

            </div>
        </div>
    <div class="container">
    <h3 class="well">Comments</h3>
    <div class="single_post_comment">
        {% for comment in comment %}
            <div class="single_comment">
                <h4><img src="http://icons.iconarchive.com/icons/icons8/ios7/512/Users-User-Male-2-icon.png" alt="" style="height: 27px;margin-right: 10px;">{{ comment.name }}</h4>
                <p>{{ comment.post_comment }}</p>
            </div>
            {% empty %}
            <h3>Sorry no comment found</h3>
        {% endfor %}

    </div>

        <div class="panel panel-success">
          <div class="panel-heading">
            <h3 class="panel-title">Comment</h3>
          </div>
          <div class="panel-body">
              <form action="" method="POST">
                  {% csrf_token %}
                  {{ form.as_p }}
                  <button class="btn btn-primary">Comment</button>
              </form>
          </div>
        </div>
    </div>
	</div>
{% endblock %}
{% block script %}

{% endblock %}

djangoblog/templates/topics.html
{% extends 'base.html' %}
{% block title %}
All topics
{% endblock %}
{% block stylesheet %}

{% endblock %}
{% block profile %}
{% endblock %}
{% block content %}
<div class="container">
    {% if messages %}
    <div class="messages">
        {% for message in messages %}
        <div {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</div>
        {% endfor %}
    </div>
    {% endif %}
    {% if request.user.is_authenticated %}
        {% if request.user.is_staff or request.user.is_superuser %}
            <a href="{% url 'blog:createTopic' %}" class="btn btn-primary pull pull-right">Add new category</a>
        {% endif %}
    {% endif %}

    <table class="table table-striped">
        <thead>
        <tr>
            <td>Topics</td>

            {% if request.user.is_authenticated %}
                {% if request.user.is_staff or request.user.is_superuser %}
                    <td>Action</td>
                {% endif %}
            {% endif %}
        </tr>
        </thead>
        <tbody>
        {% for t in topic %}
            <tr>
                <td><a href="{% url 'blog:topic' name=t.name %}">{{ t.name }}</a></td>

                {% if request.user.is_authenticated %}
                    {% if request.user.is_staff or request.user.is_superuser %}
                        <td><a href="">Delete</a>||<a href="">Edit</a></td>
                    {% endif %}
                {% endif %}
            </tr>
        {% endfor %}

        </tbody>
</table>
    </div>
{% endblock %}
{% block script %}

{% endblock %}